name: Chromatic deployment

on:
  pull_request:
    branches:
      - dev/storybook

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed_files:
    name: Checkout changed-files
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed_files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed_files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            apps/storybook/**

  chromatic:
    name: Run visual tests
    needs: changed_files
    if: ${{ needs.changed_files.outputs.any_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: apps/storybook/package.json
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build storybook
        run: npm run build

      - name: Run chromatic
        id: 'chromatic'
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          exitOnceUploaded: true
          onlyChanged: true
          skip: '@(renovate/**|dependabot/**)'

      - name: Comment in PR
        if: ${{ steps.chromatic.outcome == 'success' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: '🚀 storybook: ${{ steps.chromatic.outputs.storybookUrl }}'
          reactions: rocket
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
